### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by esjsmith** [Trudko/wrap-selection#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.4
**Thrown From**: [wrap-selection](https://github.com/Trudko/wrap-selection) package, v0.1.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/emilypatonay/.atom/packages/wrap-selection/lib/wrap-selection.coffee:14

TypeError: undefined is not a function
  at Object.module.exports.WrapSelection.wrapWithText (/Users/emilypatonay/.atom/packages/wrap-selection/lib/wrap-selection.coffee:14:29)
  at atom-text-editor.subscriptions.add.atom.commands.add.wrap-selection:wrap-with-text (/Users/emilypatonay/.atom/packages/wrap-selection/lib/wrap-selection.coffee:8:99)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)

```
### Commands

```
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 wrap-selection:wrap-with-text (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "electron-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
electron-light-syntax, v1.2.0
emmet, v2.3.10
language-coffee-script, v0.41.0
language-gfm, v0.77.0
linter-coffeescript, v0.2.1
markdown-preview, v0.150.0
minimap, v4.10.0
snippets, v0.94.0
terminal-status, v1.6.8
wrap-selection, v0.1.2

# Dev
No dev packages
```

**Comment by nlaplante** [comment]
:+1:

**Comment by majman** [comment]
same here... 

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [wrap-selection](https://github.com/Trudko/wrap-selection) package, v0.1.2

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "mac-classic"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
mac-classic, v0.3.0
minimap, v4.10.1
wrap-selection, v0.1.2

# Dev
No dev packages
```

**Comment by ryanmclaughlin** [comment]
+1

**Comment by Trudko** [comment]
Guys will take a look at this on Friday. Didn't know anybody uses this plugin :)

**Comment by Trudko** [comment]
Fixed.
